### ISSUE TITLE
Ship fewer default features

### ISSUE THREAD

**Issue by bglw** [bnjjj/twelf#17]
Hi 👋 

Loving this crate so far — the only hiccup I found was having to pare back the features. Having to to the `default-features = false` dance can be a pain.

Acutely, the `dhall` feature, on the `x86_64-unknown-linux-musl` target, includes a dependency tree of reqwest/hyper/hyper-tls/openssl, which does not play nice when trying to cross compile the openssl bindings there. 

Under the assumption that most users are unlikely to use every configuration format, making these heavier features opt-in would be great for compile speeds.

**Comment by bnjjj** [comment]
I agree, I should fix that using `cargo hack check --each-feature --no-dev-deps`  https://github.com/taiki-e/cargo-hack#--each-feature and fix compilation issues. I don't have time right now but could be a good first issue

**Comment by bnjjj** [comment]
Published on v`0.7.0` thanks @ThibsG
