### ISSUE TITLE
Support Vec<T> supplied through clap

### ISSUE THREAD

**Issue by bglw** [bnjjj/twelf#23]
Currently Twelf only uses the `value_of` method (superseded by `get_one`) on clap matches. For list arguments, this only returns the first argument in the list.
There should be a way to tell Twelf to use the `values_of` (superseded by `get_many`) function for these types instead, for in the current state one can receive a `Vec` via config files, but not through the CLI.

Relevant code:
https://github.com/bnjjj/twelf/blob/e8de938eacf496af118e136d30e29ef4eb172cff/config-derive/src/lib.rs#L213-L221

**Comment by w0xel** [comment]
Fixed as of v0.8.0
